spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: colors

logging:
  level:
    root: INFO

server:
  port: 8091

info:
    java:
      source: ${java.version}
      target: ${java.version}

---

spring:
  profiles: aws-production
  data:
    mongodb:
      host: db.fav-color.com

logging:
  level:
    root: INFO

---

spring:
  profiles: docker-production
  data:
    mongodb:
      host: mongodb

logging:
  level:
    root: INFO
